# Generated by Django 6.0.6 on 2026-06-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descrption',
            new_name='description',
        ),
    ]
