# Generated by Django 6.0.6 on 2026-06-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_descrption_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
