# Generated by Django 6.0.6 on 2026-06-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.URLField(blank=True, null=True),
        ),
    ]
