# Generated by Django 6.0.6 on 2026-06-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.BooleanField(default=False),
        ),
    ]
