# Generated by Django 6.0.6 on 2026-06-14 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='autor',
        ),
    ]
