# Generated by Django 6.0.6 on 2026-06-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactmessage_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['id'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
